---
- hosts: appserver
  become: yes
  tasks:
  - name:
    apt:
      name: apache2
      state: present
  - name: starting the apache2 service
    service: 
      name: apache2
      state: started
    - name: updating packages
      apt:
        update_cache: yes
    - name: installing Tomcat server
      apt:
        name: tomcat7
        state: present
    - name: download jenklins
      get_url:
        dest: /var/lib/tomcat7/webapps
        url: <>
    - name: copying the path
      copy:
        