---
- hosts: webserver
  sudo: yes
  tasks:
  - name: update packages
    apt:
      update_cache: yes 
  - name:
    apt:
      name: apache2
      state: present
  - name: starting the apache2 service
    service: 
      name: apache2
      state: started
  - name: creating the file
    file:
      path: /var/wwww/html/index.html
      state: file
 

