--- # installing multiple packages
- hosts: webserver
  become: yes
  gather_facts: no
  tasks:
  - name: install multipackages
    apt:
      name: "{{ items }}"
      state: present
    with_items:
    - tree
    - git
    - nano